### ISSUE TITLE
table method doesn't exist on PDOMapper class

### ISSUE THREAD

**Issue by steadweb** [reservat/core#12]
I'd suggest we make it abstract so the components extend them which defines the table. @PWesterdale already done this for Customer.

**Comment by PWesterdale** [comment]
That was my bad, I appear to have accidentally deleted it! :hankey:

**Comment by PWesterdale** [comment]
Was not my bad. was deliberately left out, the table function is in SQLDataMapperInterface :)

**Comment by steadweb** [comment]
Ya :+1: 

I think making making the class abstract is enough to cover that.

https://github.com/reservat/core/blob/master/src/Core/Datamapper/PDODatamapper.php#L7
